function props = getFluidProps_REFPROP(RP,fluid,T,P)

% GETFLUIDPROPS Retrieve common thermophysical properties from NIST REFPROP.
%
% DESCRIPTION
%   Returns a structure containing selected thermophysical properties
%   of a specified fluid at the supplied temperature and pressure using
%   NIST REFPROP.
%
% INPUTS
%   RP      - Initialized REFPROP library object.
%
%   fluid   - Fluid name recognized by REFPROP.
%             Examples:
%                 'HELIUM'
%                 'HYDROGEN'
%                 'CO2'
%                 'METHANE'
%                 'WATER'
%                 'XENON'
%
%   T       - Temperature [K]
%
%   P       - Pressure [kPa]
%
% OUTPUT
%   props   - Structure containing:
%
%       props.rho
%           Density [kg/m^3]
%
%       props.mu
%           Dynamic viscosity [Pa·s]
%
%       props.Z
%           Compressibility factor [-]
%
%       props.MW
%           Molecular weight [kg/mol]
%
% EXAMPLE
%   He = getFluidProps(RP,'HELIUM',293.15,5100);
%

props = struct();

% Pure-fluid mole fraction vect
z = py.list({1.0});

% Molecular weight [g/mol]
out = RP.REFPROPdll( ...
    fluid,...
    'TP',...
    'M',...
    int32(0),...
    int32(0),...
    int32(0),...
    T,...
    P,...
    z);
MW_gmol = double(out.Output(1));
props.MW = MW_gmol/1000;      % kg/mol

% Density [mol/L]
out = RP.REFPROPdll( ...
    fluid,...
    'TP',...
    'D',...
    int32(0),...
    int32(0),...
    int32(0),...
    T,...
    P,...
    z);
rho_molL = double(out.Output(1));
props.rho = rho_molL*MW_gmol;% mol/L * g/mol = kg/m^3 numerically

% Compressibility factor
out = RP.REFPROPdll( ...
    fluid, ...
    'TP', ...
    'Z', ...
    int32(0), ...
    int32(0), ...
    int32(0), ...
    T, ...
    P, ...
    z);

props.Z = double(out.Output(1));

% Viscosity [μPa·s]
out = RP.REFPROPdll( ...
    fluid, ...
    'TP', ...
    'VIS', ...
    int32(0), ...
    int32(0), ...
    int32(0), ...
    T, ...
    P, ...
    z);
mu_microPas = double(out.Output(1));
props.mu = mu_microPas*1e-6;   % Pa·s

end
