function props = getMixtureProps_REFPROP(RP,fluids,z,T,P)

% fluids
%   {'HELIUM','XENON'}
%
% z
%   mole fractions
%   [0.25 0.75]
%
% T [K]
% P [kPa]

props = struct();

% REFPROP mixture string
fluidString = strjoin(fluids,'*');

% REFPROP composition vector
zREF = zeros(1,20);
zREF(1:length(z)) = z;
zREF = py.list(num2cell(zREF));

% Density
out = RP.REFPROPdll( ...
    fluidString,...
    'TP',...
    'D',...
    int32(0),...
    int32(0),...
    int32(0),...
    T,...
    P,...
    zREF);

D_molL = double(out.Output(1));

% Molecular weight from mole fractions
MW = 0;
for k = 1:length(fluids)
    pure = getFluidProps_REFPROP( ...
        RP,...
        fluids{k},...
        T,...
        P);
    MW = MW + z(k)*pure.MW;
end

% Convert density
props.rho = D_molL*(MW*1000);

% Compressibility
out = RP.REFPROPdll( ...
    fluidString,...
    'TP',...
    'Z',...
    int32(0),...
    int32(0),...
    int32(0),...
    T,...
    P,...
    zREF);

props.Z = double(out.Output(1));
props.MW = MW;

end
