function MFM_data = import_MFM_data(filename,dataLines)
%IMPORTFILE Import data from a text file
%  BRONKHORSTFLOWSUITEEXPORT20250402195014 = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  BRONKHORSTFLOWSUITEEXPORT20250402195014 = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  BronkhorstFlowSuiteExport20250402195014 = importfile("C:\Users\igome\OneDrive - The Pennsylvania State University\06_PHD_EME_PSU\00 PhD RESEARCH\RESEARCH\H2 DISPLACEMENT EXPERIMENT\Experimental data\CF 04-02-25\Bronkhorst FlowSuite Export 2025_04_02 19_50_14.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Apr-2025 10:58:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 3
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "qset_MFM2", "AnalogInput_MFM2", "ValveOutput_MFM2", "q_MFM2", "T_MFM2", "dens_MFM2", "freq_MFM2", "q_MFM1", "T_MFM1"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TimeStamp", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");

% Import the data
MFM_data = readtable(filename, opts);

% Preparing time data

MFM_data.TimeStamp.Format = 'MM/dd/uuuu HH:mm:ss.SSS';

% data_datetime = MFM_data.TimeStamp;
% 
% MFM_data_ftime = addvars(MFM_data,data_datetime);
% MFM_data_ftime = removevars(MFM_data_ftime,"TimeStamp");
% 
% MFM_data_ftime = table2timetable(MFM_data_ftime);
% 
% toRemove = isnat(MFM_data_ftime.data_datetime);
% MFM_data_ftime(toRemove,:) = [];
% %MFM_data_ftime = rmmissing(MFM_data_ftime);
% 
% MFM_data_ftime = retime(MFM_data_ftime,unique(MFM_data_ftime.data_datetime));

end