function trans_data = import_trans_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OMEGAUSBHLOG20250402113920 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  OMEGAUSBHLOG20250402113920 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  omegaUSBHLog20250402113920 = importfile("C:\Users\igome\OneDrive - The Pennsylvania State University\06_PHD_EME_PSU\00 PhD RESEARCH\RESEARCH\H2 DISPLACEMENT EXPERIMENT\Experimental data\CF 04-02-25\omega USBH Log 2025-04-02 113920.csv", [12, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Apr-2025 11:01:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [12, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time_PT1", "PT1", "Time_PT2", "PT2"];
opts.VariableTypes = ["datetime", "double", "datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time_PT1", "InputFormat", "yyyy-MM-dd hh:mm:ss.SSS aa");
opts = setvaropts(opts, "Time_PT2", "InputFormat", "yyyy-MM-dd hh:mm:ss.SSS aa");

% Import the data
trans_data = readtable(filename, opts);

% Preparing time data
trans_data.Time_PT1.Format = 'MM/dd/uuuu HH:mm:ss.SSS';
trans_data.Time_PT2.Format = 'MM/dd/uuuu HH:mm:ss.SSS';

trans_data = renamevars(trans_data, 'Time_PT1', 'TimeStamp_PT1');
trans_data = renamevars(trans_data, 'Time_PT2', 'TimeStamp_PT2');

% 
% data_datetime = trans_data.Time_PT1;
% dt = trans_data.PT2 - trans_data.PT2;
% 
% trans_data_ftime = addvars(trans_data,data_datetime, dt);
% trans_data_ftime = removevars(trans_data_ftime,["Time_PT1","Time_PT2"]);
% 
% trans_data_ftime = table2timetable(trans_data_ftime);
% 
% toRemove = isnat(trans_data_ftime.data_datetime);
% trans_data_ftime(toRemove,:) = [];
% %trans_data_ftime = rmmissing(trans_data_ftime);
% 
% trans_data_ftime = retime(trans_data_ftime,unique(trans_data_ftime.data_datetime));
end