function dataRef_out = import_inputRef(inputRef_name_xlsx)

%IMPORT_INPUTREF Import reference thermodynamic-property data.
%
%   DATAREF_OUT = IMPORT_INPUTREF(INPUTREF_NAME_XLSX) imports reference
%   fluid-property data from an Excel workbook and returns the results as
%   a MATLAB table.
%
%   The imported dataset is typically used for validation of
%   thermodynamic-property calculations, comparison against equation-of-
%   state predictions, and benchmarking density or compressibility-factor
%   estimates against trusted reference values.
%
%   INPUT
%       inputRef_name_xlsx
%           Path to the Excel workbook containing reference-property data.
%
%   OUTPUT
%       dataRef_out
%           MATLAB table containing the imported reference properties.
%
%   EXPECTED SPREADSHEET FORMAT
%       The workbook is expected to contain a worksheet named:
%
%           Sheet1
%
%       with data beginning on row 3 and the following columns:
%
%           Fluid      Fluid name
%           T_C        Temperature [°C]
%           P_psig     Pressure [psig]
%           P_psia     Pressure [psia]
%           P_bar      Pressure [bar]
%           P_MPa      Pressure [MPa]
%           dens       Density [kg/m^3]
%           Z          Compressibility factor [-]
%           Phase      Fluid phase designation
%
%   APPLICATIONS
%       The imported data can be used for:
%
%           - Validation of Peng-Robinson EOS predictions
%           - Density comparisons
%           - Compressibility-factor comparisons
%           - Thermodynamic consistency checks
%           - Literature-data benchmarking
%
%   RETURNED VARIABLES
%       Fluid
%           Fluid identifier
%
%       T_C
%           Temperature [°C]
%
%       P_psig
%           Gauge pressure [psig]
%
%       P_psia
%           Absolute pressure [psia]
%
%       P_bar
%           Pressure [bar]
%
%       P_MPa
%           Pressure [MPa]
%
%       dens
%           Reference density [kg/m^3]
%
%       Z
%           Reference compressibility factor [-]
%
%       Phase
%           Reported fluid phase
%
%   NOTES
%       - Designed for importing reference thermodynamic-property data.
%       - Assumes worksheet name "Sheet1".
%       - Assumes data begin at row 3.
%       - Returns values exactly as stored in the spreadsheet.
%       - Typically used for comparison against EOS predictions
%         generated by DENSZ_PR.
%
%   EXAMPLE
%       refData = import_inputRef('Reference_Properties.xlsx');
%
%       plot(refData.P_MPa, refData.Z, 'o')
%       xlabel('Pressure (MPa)')
%       ylabel('Compressibility Factor, Z')
%
%   See also DENSZ_PR, CALC_Z, READTABLE,
%            SPREADSHEETIMPORTOPTIONS.

opts = spreadsheetImportOptions("NumVariables", 8);
% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = [3,Inf];
% Specify column names and types
opts.VariableNames = ["Fluid", "T_C", "P_psig", "P_psia", "P_bar", "P_MPa", "dens", "Z", "Phase"];
opts.VariableTypes = ["string", "double","double", "double", "double", "double", "double", "double", "string"];
dataRef_out = readtable(inputRef_name_xlsx,opts);
end

