function PGD2_data = import_PGD2_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  XP3340II20100003MEASUREMENTRAWDATA20241210040517 =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  XP3340II20100003MEASUREMENTRAWDATA20241210040517 = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  XP3340II20100003Measurementrawdata20241210040517 = importfile("C:\Users\igome\OneDrive - The Pennsylvania State University\06_PHD_EME_PSU\00 PhD RESEARCH\RESEARCH\H2 DISPLACEMENT EXPERIMENT\Experimental data\CF 04-04-25\XP-3340II_20100003_Measurement raw data_20241210040517.csv", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Apr-2025 11:17:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "CO2Temperature", "CO2Humidity", "CO2AL1", "CO2AL2", "CO2Error", "CO2ReferenceConcentration", "CO2Overrange", "CO2GasConcentration"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "time", "InputFormat", "yyyy/MM/dd HH:mm:ss.SSS");

% Import the data
PGD2_data = readtable(filename, opts);

% Preparing data
PGD2_data.time.Format = 'MM/dd/uuuu HH:mm:ss.SSS';

PGD2_data = renamevars(PGD2_data,'time','TimeStamp');

% data_datetime = PGD2_data.time;
% 
% PGD2_data_ftime = addvars(PGD2_data,data_datetime);
% PGD2_data_ftime = removevars(PGD2_data_ftime,"time");
% 
% PGD2_data_ftime = table2timetable(PGD2_data_ftime);
% 
% toRemove = isnat(PGD2_data_ftime.data_datetime);
% PGD2_data_ftime(toRemove,:) = [];
% % PGD2_data_ftime = rmmissing(PGD2_data_ftime);
% 
% PGD2_data_ftime = retime(PGD2_data_ftime,unique(PGD2_data_ftime.data_datetime));

end