function KL_lines = KL_lines_taylor_aris(v, r, Dm)

%KL_LINES_TAYLOR_ARIS Calculate Taylor-Aris dispersion in tubing.
%
%   KL_LINES_TAYLOR_ARIS(V,R,DM) computes the effective longitudinal
%   dispersion coefficient for laminar flow in a cylindrical tube using
%   the classical Taylor-Aris dispersion model.
%
%   INPUTS
%       v     : Average fluid velocity [m/s]
%
%       r     : Internal tube radius [m]
%
%       Dm    : Molecular diffusion coefficient [m^2/s]
%
%   OUTPUT
%       KL_lines
%             : Effective longitudinal dispersion coefficient in the
%               tubing [m^2/s]
%
%   MODEL DESCRIPTION
%       The Taylor-Aris theory describes the enhancement of longitudinal
%       dispersion caused by the interaction between:
%
%           - Molecular diffusion
%           - Laminar velocity gradients
%
%       in a cylindrical tube.
%
%       The effective dispersion coefficient is:
%
%                     v^2 r^2
%           KL = Dm + --------
%                      48 Dm
%
%       where:
%
%           Dm  = molecular diffusion coefficient
%           v   = average fluid velocity
%           r   = tube radius
%
%   PHYSICAL INTERPRETATION
%       The first term:
%
%           Dm
%
%       represents molecular diffusion.
%
%       The second term:
%
%               v^2 r^2
%           -------------
%              48 Dm
%
%       represents dispersion generated by the parabolic velocity profile
%       in laminar pipe flow.
%
%       As fluid velocity increases, Taylor dispersion becomes
%       increasingly important and may dominate over molecular diffusion.
%
%   APPLICATIONS
%       This function is intended for estimating dispersion occurring in:
%
%           - Experimental tubing
%           - Injection lines
%           - Sampling lines
%           - Core-flood manifolds
%           - Other cylindrical flow conduits
%
%       The resulting KL_lines value can be used to assess the impact of
%       extra-core transport on measured breakthrough curves.
%
%   ASSUMPTIONS
%       - Laminar flow.
%       - Cylindrical tubing geometry.
%       - Fully developed velocity profile.
%       - Constant fluid properties.
%       - Long-time Taylor-Aris regime.
%
%   EXAMPLE
%       v = 0.01;      % m/s
%       r = 0.0008;    % m
%       Dm = 1e-7;     % m^2/s
%
%       KL_lines = KL_lines_taylor_aris(v,r,Dm);
%
%   See also CALC_DIFF_MARRERO.

    KL_lines = Dm + (v^2 * r^2) / (48 * Dm);
end