%% main_DataExtract.m
% Author: Ianna Gomez Mendez
%
% PURPOSE
%   Process core-flood and tracer-transport experiments and generate
%   breakthrough-curve (BTC) datasets from raw acquisition files.
%
%   The workflow imports experimental measurements, applies Coriolis
%   density calibration corrections, estimates fluid composition using
%   Peng-Robinson EOS calculations, computes transport-related dimensionless
%   parameters, and exports processed datasets for subsequent dispersion
%   and breakthrough-curve analyses.
%
% -------------------------------------------------------------------------
% EXPERIMENTAL SYSTEM
% -------------------------------------------------------------------------
%
%   Measurements may include:
%
%       - Quizix syringe pumps
%       - Bronkhorst Coriolis mass flow meter (MFM)
%       - Omega pressure transducers
%       - Cosmos portable gas detectors (PGD1, PGD2)
%
%   Only pump and MFM datasets are strictly required.
%
% -------------------------------------------------------------------------
% INPUT FILES
% -------------------------------------------------------------------------
%
% Configuration:
%
%       inputExpConfig.xlsx
%
% Experimental metadata:
%
%       inputExp.xlsx
%
% Thermodynamic-property files:
%
%       - Pure-component PR EOS parameters
%       - Binary interaction parameter (BIP) coefficients
%       - Marrero diffusion-correlation coefficients
%
% Calibration files generated by main_Cal.m:
%
%       fittingRhoResultsAll.mat
%       nlfittingRhoResultsAll.mat
%       cal_curve_params.mat
%       nl_cal_curve_params.mat
%
% Experimental acquisition files:
%
%       Pumps (.dat)
%       Pressure transducers (.csv)
%       MFM (.csv)
%       PGD1 (.csv)
%       PGD2 (.csv)
%
% -------------------------------------------------------------------------
% WORKFLOW
% -------------------------------------------------------------------------
%
%   1. Import experiment metadata.
%
%   2. Import Peng-Robinson EOS parameters.
%
%   3. Import Marrero diffusion-correlation parameters.
%
%   4. Import and synchronize experimental datasets.
%
%   5. Trim all datasets using experiment start and end times.
%
%   6. Calculate:
%
%          - Time elapsed
%          - Injected volume
%          - Interstitial velocity
%          - Tubing lengths
%          - Tubing dispersion coefficients
%
%   7. Estimate molecular diffusion coefficients using the
%      Marrero correlation.
%
%   8. Apply Coriolis density calibration obtained from calibration
%      experiments.
%
%   9. Generate breakthrough-curve datasets.
%
%  10. Estimate fluid composition from corrected density measurements
%      using Peng-Robinson EOS interpolation.
%
%  11. Calculate:
%
%          - Composition uncertainty
%          - Compressibility factor
%          - Dimensionless pore volumes injected
%          - Normalized concentration
%
%  12. Export processed datasets and figures.
%
% -------------------------------------------------------------------------
% TRANSPORT PARAMETERS
% -------------------------------------------------------------------------
%
%   Core properties are used to calculate:
%
%       A          Core cross-sectional area
%       L          Core length
%       q          Volumetric flow rate
%       v          Darcy velocity
%       u          Interstitial velocity
%
%   Tubing properties are used to calculate:
%
%       L_linesbefore
%       L_linesafter
%       KL_lines
%
%   where KL_lines is estimated using:
%
%       Taylor-Aris dispersion theory
%
% -------------------------------------------------------------------------
% DENSITY CALIBRATION
% -------------------------------------------------------------------------
%
%   Raw MFM density measurements are corrected using calibration
%   parameters generated by MAIN_CAL.
%
%   The calibrated density is subsequently used as the primary state
%   variable for composition estimation.
%
% -------------------------------------------------------------------------
% COMPOSITION ESTIMATION
% -------------------------------------------------------------------------
%
%   For each experiment:
%
%       1. Peng-Robinson EOS calculations are generated over a grid of:
%
%              Pressure
%              Temperature
%              Composition
%
%       2. A scattered interpolation model is created:
%
%              x1 = f(T,P,rho)
%
%       3. Corrected densities are converted to molar compositions.
%
%   The resulting breakthrough curve contains:
%
%       Ci
%       dC
%       Z
%       dZ
%
%   and associated uncertainty estimates.
%
% -------------------------------------------------------------------------
% BREAKTHROUGH-CURVE VARIABLES
% -------------------------------------------------------------------------
%
%   BT includes:
%
%       TimeStamp
%       TimeElapsed
%       SecondsElapsed
%
%       rho_MFM
%       rho_corr
%       rho_corrMin
%       rho_corrMax
%
%       T_MFM
%       q_MFM
%
%       Ci
%       CiMin
%       CiMax
%       dC
%
%       Z
%       dZ
%
%       tD
%       tDtotal
%
%       CDi
%       CDiMin
%       CDiMax
%
% -------------------------------------------------------------------------
% OUTPUTS
% -------------------------------------------------------------------------
%
% MATLAB databases:
%
%       expProcData.mat
%
% Per-experiment spreadsheets:
%
%       <Key>.xlsx
%
% containing:
%
%       pumps_data
%       trans_data
%       MFM_data
%       PGD1_data
%       PGD2_data
%       exp_params
%       BT_curve
%
% Figures:
%
%       <Key>_BT_All_Vars.png
%       <Key>_dens_conc.png
%
% -------------------------------------------------------------------------
% DEPENDENCIES
% -------------------------------------------------------------------------
%
% Import functions:
%
%       import_inputExp
%       import_pumps_data
%       import_trans_data
%       import_MFM_data
%       import_PGD1_data
%       import_PGD2_data
%
% Thermodynamic functions:
%
%       densZ_PR
%       calc_BIP
%       calc_ai_bi
%
% Diffusion correlations:
%
%       calc_diff_marrero
%
% Transport calculations:
%
%       KL_lines_taylor_aris
%
% Calibration results:
%
%       main_Cal.m outputs
%
% -------------------------------------------------------------------------
% NOTES
% -------------------------------------------------------------------------
%
%   - Composition estimates are only as accurate as the density
%     calibration and EOS model.
%
%   - Binary-mixture calculations assume only two fluid components.
%
%   - Pressure-transducer data improve composition estimation by
%     accounting for pressure variations during experiments.
%
%   - The resulting BT datasets constitute the primary input for
%     dispersion-coefficient estimation and transport-model fitting.

%% IMPORT input

addpath('functions/');

% Introduce name of input and desired output folder name

inputFileConfigName = 'inputExpConfig.xlsx';

inputFileConfig = readtable(inputFileConfigName);

filenameExp = inputFileConfig.inputFileName{:};

% PR parameters
% INTRODUCE THE INPUT HERE
% file containing pure components NIST data: Tc, Pc and acentric factor w
filenamePure = inputFileConfig.inputPureParams{:};
% file containing mixture compoents A12 B12 factor to estimate BIP
filenameBIP = inputFileConfig.inputMixParams{:};
% file diffusion params Marrero to calculate D12 effective diffusion
% coefficient using Marrero mold
filenameDiff = inputFileConfig.inputDiffModel{:};

% cal curve results input import
pathImportCal = inputFileConfig.importPath{:};

pathExportAll = inputFileConfig.exportPath{:}; % Path for OUTPUT
mkdir(pathExportAll); % Create directory for output

%% IMPORT data

filedataExp = import_inputExp(filenameExp); % import input to a local variable

% import pure components NIST data: Tc, Pc and acentric factor w
filedataPure = import_inputPR_params_pure(filenamePure);
% import mixture components A12 and B12 factor to estimate BIP (kij)
filedataBIP = import_inputPR_params_BIP(filenameBIP);
% import file diffusion params Marrero
filedataDiff = import_params_diffusion_marrero(filenameDiff);

for i = 1:length(filedataExp.Key)
    pumps_data_name = filedataExp.path(i) + filedataExp.pumps_data_name(i);
    trans_data_name = filedataExp.path(i) + filedataExp.trans_data_name(i);
    MFM_data_name = filedataExp.path(i) + filedataExp.MFM_data_name(i);
    PGD1_data_name = filedataExp.path(i) + filedataExp.PGD1_data_name(i);
    PGD2_data_name = filedataExp.path(i) + filedataExp.PGD2_data_name(i);
    
    % pumps in local variables
    workingPump = filedataExp.workingPump(i);
    cushionPump = filedataExp.cushionPump(i);
    confPump = filedataExp.confiningPump(i);
    
    if ismissing(pumps_data_name) == 0
        pumps_data = import_pumps_data(pumps_data_name, workingPump, confPump, cushionPump); % import pumps data to local variable
        % Trim data to st and et
        expProcData.(filedataExp.Key(i)).pumpsData = pumps_data ...
            ((pumps_data.TimeStamp>=filedataExp.st(i))& ...
            (pumps_data.TimeStamp<=filedataExp.et(i)),:); % import pumps data from st (start time) to et (end time) to struct.Key
        % Calculate time elapsed
        expProcData.(filedataExp.Key(i)).pumpsData.TimeElapsed = expProcData.(filedataExp.Key(i)).pumpsData.TimeStamp - filedataExp.st(i);
        expProcData.(filedataExp.Key(i)).pumpsData.TimeElapsed.Format = 'hh:mm:ss.SSS';
        % Calculate vol injected
        expProcData.(filedataExp.Key(i)).pumpsData.VolInjected = expProcData.(filedataExp.Key(i)).pumpsData.V_P1 - expProcData.(filedataExp.Key(i)).pumpsData.V_P1(1);
    end

    if ismissing(MFM_data_name) == 0
        MFM_data = import_MFM_data(MFM_data_name); % import MFM2 data to local variable
        % Trim data to st and et
        expProcData.(filedataExp.Key(i)).MFMData = MFM_data ...
            ((MFM_data.TimeStamp>=filedataExp.st(i))& ...
            (MFM_data.TimeStamp<=filedataExp.et(i)),:); % import MFM2 data from st (start time) to et (end time) to struct.Key
        % Calculate time elapsed
        expProcData.(filedataExp.Key(i)).MFMData.TimeElapsed = expProcData.(filedataExp.Key(i)).MFMData.TimeStamp - filedataExp.st(i);
        expProcData.(filedataExp.Key(i)).MFMData.TimeElapsed.Format = 'hh:mm:ss.SSS';
    end

    if ismissing(trans_data_name) == 0
        trans_data = import_trans_data(trans_data_name); % import p transducer data to local variable
         % Trim data to st and et
        expProcData.(filedataExp.Key(i)).transData = trans_data ...
            ((trans_data.TimeStamp_PT1>=filedataExp.st(i))& ...
            (trans_data.TimeStamp_PT1<=filedataExp.et(i)),:); % import p trans data from st (start time) to et (end time) to struct.Key
        % Calculate time elapsed
        expProcData.(filedataExp.Key(i)).transData.TimeElapsed = expProcData.(filedataExp.Key(i)).transData.TimeStamp_PT1 - filedataExp.st(i);
        expProcData.(filedataExp.Key(i)).transData.TimeElapsed.Format = 'hh:mm:ss.SSS';
    end

    if ismissing(PGD1_data_name) == 0
        PGD1_data = import_PGD1_data(PGD1_data_name); % import PGD1 data to local variable
        % Change time if other GMT
        if filedataExp.GMT_PGD{i} == "GMT9"
            PGD1_data.TimeStamp = PGD1_data.TimeStamp - hours(13); %ONLY if PGD in Japan time GMT+9    
        end
        % Trim data to st and et
        expProcData.(filedataExp.Key(i)).PGD1Data = PGD1_data ...
            ((PGD1_data.TimeStamp>=filedataExp.st(i))& ...
            (PGD1_data.TimeStamp<=filedataExp.et(i)),:); % import PGD1 data from st (start time) to et (end time) to struct.Key
        % Calculate time elapsed
        expProcData.(filedataExp.Key(i)).PGD1Data.TimeElapsed = expProcData.(filedataExp.Key(i)).PGD1Data.TimeStamp - filedataExp.st(i);
        expProcData.(filedataExp.Key(i)).PGD1Data.TimeElapsed.Format = 'hh:mm:ss.SSS';
        % C1 in vol concentration % and mol concentration % (atmospheric conditions)
        expProcData.(filedataExp.Key(i)).PGD1Data.C1 = expProcData.(filedataExp.Key(i)).PGD1Data.H2GasConcentration;
    end

    if ismissing(PGD2_data_name) == 0
        PGD2_data = import_PGD2_data(PGD2_data_name); % import PGD1 data to local variable
        % Change time if other GMT
        if filedataExp.GMT_PGD{i} == "GMT9"
            PGD2_data.TimeStamp = PGD2_data.TimeStamp - hours(13); %ONLY if PGD in Japan time GMT+9    
        end
        % Trim data to st and et
        expProcData.(filedataExp.Key(i)).PGD2Data = PGD2_data ...
            ((PGD2_data.TimeStamp>=filedataExp.st(i))& ...
            (PGD2_data.TimeStamp<=filedataExp.et(i)),:); % import PGD2 data from st (start time) to et (end time) to struct.Key
        % Calculate time elapsed
        expProcData.(filedataExp.Key(i)).PGD2Data.TimeElapsed = expProcData.(filedataExp.Key(i)).PGD2Data.TimeStamp - filedataExp.st(i);
        expProcData.(filedataExp.Key(i)).PGD2Data.TimeElapsed.Format = 'hh:mm:ss.SSS';
        % C2 in vol concentration and mol concentration (atmospheric conditions)
        expProcData.(filedataExp.Key(i)).PGD2Data.C2 = expProcData.(filedataExp.Key(i)).PGD2Data.CO2GasConcentration;
        % Because binary mixture: C1 in vol concentration % and mol concentration % (atmospheric conditions)
        expProcData.(filedataExp.Key(i)).PGD2Data.C1 = 100 - expProcData.(filedataExp.Key(i)).PGD2Data.C2;
    end

    A = pi*((filedataExp.D(i)*0.0254)/2)^2; %m2
    L = filedataExp.L(i)*0.0254; % m
    q = filedataExp.Q(i)*(10^(-6))/60; %m3/s
    v = q./A; % Darcy velocity m/s
    u = v./filedataExp.phi(i); % Interstitial velocity
    Vbefore = filedataExp.Vlinesbefore(i)/(10^6); %m3
    Vafter = filedataExp.Vlinesafter(i)/(10^6);

    % lines
    A_lines = pi*((filedataExp.IDlines_cm(i)/100)/2)^2; %m2
    v_lines = q./A_lines; %m3/s
    L_linesbefore = Vbefore/A_lines; %m
    L_linesafter = Vafter/A_lines; %m
    L_total = L_linesbefore + L_linesafter;

    % Assumes only one row is output, unique parasm for fluid 1 and 2
    filedataDiffaux = filedataDiff((filedataDiff.Fluid1 == filedataExp.Fluid1{i} & filedataDiff.Fluid2 == filedataExp.Fluid2{i}),:);
    
    %[D12, dD12] = calc_diff_marrero(T_C,P_psig, A, B, C, D, E, group, dev_pc)
    [D12,dD12] = calc_diff_marrero(filedataExp.T(i), ...
        filedataExp.P(i), filedataDiffaux.A, filedataDiffaux.B, ...
        filedataDiffaux.C, filedataDiffaux.D, filedataDiffaux.E, ...
        filedataDiffaux.group, filedataDiffaux.dev_pc); %cm2min

    % KL lines Aris Dispersion
    % KL_lines = KL_lines_taylor_aris(v, r, Dm)
    KL_lines =  KL_lines_taylor_aris(v_lines, filedataExp.IDlines_cm(i)/100, D12/(60*(10^4)));

    exp_params = table(filedataExp.Key(i), filedataExp.Date(i), filedataExp.Type(i), filedataExp.Fluid1(i), filedataExp.Fluid2(i), ...
        D12, dD12,...
        filedataExp.T(i), filedataExp.P(i), filedataExp.Q(i), filedataExp.C1init(i), filedataExp.C1j(i), filedataExp.Run(i), ...
        filedataExp.D(i), filedataExp.L(i), filedataExp.phi(i), filedataExp.K(i), filedataExp.Vcore(i), ...
        filedataExp.setupVersion(i), filedataExp.IDlines_cm(i), filedataExp.Vlinesbefore(i), filedataExp.Vlinesafter(i), ... 
        L_linesbefore, L_linesafter, filedataExp.Vtotal(i), L_total, ...
        A,L,q,v,u, A_lines, v_lines, KL_lines,KL_lines*60*(10^4), 'VariableNames', {'Key', 'Date', 'Type','Fluid1', 'Fluid2', ...
        'D12_cm2min', 'dD12_cm2min',...
        'T_C', 'P_psig', 'Q_mlmin', 'C1init_pcmol', 'C1j_pcmol', 'Run', 'D_in', 'L_in', 'phi', 'K_mD', 'Vcore_cc', ...
        'setupVersion', 'ID_lines_cm', 'Vlinesbefore_cc', 'Vlinesafter_cc', ...
        'L_linesbefore_SI', 'L_linesafter_SI', 'Vtotal_cc', 'L_linestotal_SI' ...
        'A_SI','L_SI','q_SI','v_SI','u_SI', ...
        'A_lines_SI','v_lines_SI','KL_lines_SI', 'KL_lines_cm2min'});
    expProcData.(filedataExp.Key(i)).exp_params = exp_params;

end

load(pathImportCal + "fittingRhoResultsAll.mat")
load(pathImportCal + "nlfittingRhoResultsAll.mat")
load(pathImportCal + "nlQfittingRhoResultsAll.mat")

load(pathImportCal + "cal_curve_params.mat");
load(pathImportCal + "nl_cal_curve_params.mat");
load(pathImportCal + "nl_Q_cal_curve_params.mat");

%% Extract breakthrough curve data

%rho_corr_lin function
rho_corr_lin = @(p,y) (y-p(1))/p(2);

% rho_corr_nl function second part
rho_corr_nlin = @(p,rho_MFM) (rho_MFM-p(1)+p(3)*p(4))/(p(3)+p(2));

for i = 1:length(filedataExp.Key)
    trans_data_name = filedataExp.path(i) + filedataExp.trans_data_name(i);
    % Extrat measured density vs time
    BTaux = table(expProcData.(filedataExp.Key(i)).MFMData.TimeStamp, ...
        expProcData.(filedataExp.Key(i)).MFMData.TimeElapsed, ...
        seconds(expProcData.(filedataExp.Key(i)).MFMData.TimeElapsed), ...
        expProcData.(filedataExp.Key(i)).MFMData.dens_MFM2, ...
        expProcData.(filedataExp.Key(i)).MFMData.T_MFM2, ...
        expProcData.(filedataExp.Key(i)).MFMData.q_MFM2, ...
        'VariableNames',{'TimeStamp','TimeElapsed', 'SecondsElapsed', 'rho_MFM','T_MFM','q_MFM'});
    if ismissing(trans_data_name) == 0
        BTaux_timetable = table2timetable(BTaux);
        PT_timetable = table2timetable(expProcData.(filedataExp.Key(i)).transData);
        BTaux_interp = retime(PT_timetable, BTaux_timetable.TimeStamp, 'linear');
        BTaux.PT2 = BTaux_interp.PT2; % psi
    end
    expProcData.(filedataExp.Key(i)).BT = BTaux;
    % fitting parameters for rho corrected
    % auxLinFit = fittingRhoResultsAll(fittingRhoResultsAll.Q == "QAll",:);
    auxnLinFit = nlfittingRhoResultsAll(nlfittingRhoResultsAll.Q == "QAll",:);
    rho_MFM_0 = auxnLinFit.rho_MFM_0;
    rho_MFM = expProcData.(filedataExp.Key(i)).BT.rho_MFM;
    % low densities
    expProcData.(filedataExp.Key(i)).BT.rho_corr = rho_corr_lin([auxnLinFit.p1,auxnLinFit.p2],rho_MFM);
    expProcData.(filedataExp.Key(i)).BT.rho_corrMin = rho_corr_lin([auxnLinFit.p1,auxnLinFit.p2],rho_MFM-auxnLinFit.drho_corr_low);
    expProcData.(filedataExp.Key(i)).BT.rho_corrMax = rho_corr_lin([auxnLinFit.p1,auxnLinFit.p2],rho_MFM+auxnLinFit.drho_corr_low);
    % high densities
    expProcData.(filedataExp.Key(i)).BT.rho_corr(rho_MFM>rho_MFM_0) = ...
        rho_corr_nlin([auxnLinFit.p1,auxnLinFit.p2,auxnLinFit.p3,auxnLinFit.p4], ...
        rho_MFM(rho_MFM>rho_MFM_0));
    expProcData.(filedataExp.Key(i)).BT.rho_corrMin(rho_MFM>rho_MFM_0) = ...
        rho_corr_nlin([auxnLinFit.p1,auxnLinFit.p2,auxnLinFit.p3,auxnLinFit.p4], ...
        rho_MFM(rho_MFM>rho_MFM_0)-auxnLinFit.drho_corr_high);
    expProcData.(filedataExp.Key(i)).BT.rho_corrMax(rho_MFM>rho_MFM_0) = ...
        rho_corr_nlin([auxnLinFit.p1,auxnLinFit.p2,auxnLinFit.p3,auxnLinFit.p4], ...
        rho_MFM(rho_MFM>rho_MFM_0)+auxnLinFit.drho_corr_high);
end

% %% Extract breakthrough curve data Q efect low density
% 
% rho_ref_0 = nlfittingRhoResultsAll.p4(nlfittingRhoResultsAll.Q == "QAll");
% nl_cal_curve_params_Qall = nl_cal_curve_params{2};
% rho_MFM_0 = predict(nl_cal_curve_params_Qall,rho_ref_0);
% 
% % rho_corr_nl function second part
% rho_corr_nlin = @(p,rho_MFM) (rho_MFM-p(1))/(p(2)); % p(1) intercept, p(2) slope
% 
% % params from fitting for each curve
% auxnLinFit_LD = nlQfittingRhoResultsAll(nlQfittingRhoResultsAll.Q == "QAll-Lrho",:);
% auxnLinFit_HD = nlQfittingRhoResultsAll(nlQfittingRhoResultsAll.Q == "QAll-Hrho",:);
% 
% % % low dens parameters depend on Q
% p_low_dens = [rho_MFM_0 - (filedataExp.Q.^auxnLinFit_LD.p5)*auxnLinFit_LD.p2*rho_ref_0,(filedataExp.Q.^auxnLinFit_LD.p5)*auxnLinFit_LD.p2];
% p_high_dens = [rho_MFM_0 - auxnLinFit_HD.m*rho_ref_0,auxnLinFit_HD.m];
% 
% for i = 1:length(filedataExp.Key)
%     Q = filedataExp.Q(i);
%     % Extrat measured density vs time
%     BTaux = table(expProcData.(filedataExp.Key(i)).MFMData.TimeStamp, ...
%         expProcData.(filedataExp.Key(i)).MFMData.TimeElapsed, ...
%         seconds(expProcData.(filedataExp.Key(i)).MFMData.TimeElapsed), ...
%         expProcData.(filedataExp.Key(i)).MFMData.dens_MFM2, ...
%         expProcData.(filedataExp.Key(i)).MFMData.T_MFM2, ...
%         expProcData.(filedataExp.Key(i)).MFMData.q_MFM2, ...
%         'VariableNames',{'TimeStamp','TimeElapsed', 'SecondsElapsed', 'rho_MFM','T_MFM','q_MFM'});
%     expProcData.(filedataExp.Key(i)).BT = BTaux;
%     % fitting parameters for rho corrected
%     rho_MFM = expProcData.(filedataExp.Key(i)).BT.rho_MFM;
%     % lower slope
%     expProcData.(filedataExp.Key(i)).BT.rho_corr = rho_corr_nlin([rho_MFM_0 - (Q^auxnLinFit_LD.p5)*auxnLinFit_LD.p2*rho_ref_0,(Q^auxnLinFit_LD.p5)*auxnLinFit_LD.p2],rho_MFM);
%     expProcData.(filedataExp.Key(i)).BT.rho_corrMin = rho_corr_nlin([rho_MFM_0 - (Q^auxnLinFit_LD.p5)*auxnLinFit_LD.p2*rho_ref_0,(Q^auxnLinFit_LD.p5)*auxnLinFit_LD.p2],rho_MFM-auxnLinFit_LD.RMSE);
%     expProcData.(filedataExp.Key(i)).BT.rho_corrMax = rho_corr_nlin([rho_MFM_0 - (Q^auxnLinFit_LD.p5)*auxnLinFit_LD.p2*rho_ref_0,(Q^auxnLinFit_LD.p5)*auxnLinFit_LD.p2],rho_MFM+auxnLinFit_LD.RMSE);
%     % higher slope
%     expProcData.(filedataExp.Key(i)).BT.rho_corr(rho_MFM>rho_MFM_0) = ...
%         rho_corr_nlin([rho_MFM_0 - auxnLinFit_HD.m*rho_ref_0,auxnLinFit_HD.m], ...
%         rho_MFM(rho_MFM>rho_MFM_0));
%     expProcData.(filedataExp.Key(i)).BT.rho_corrMin(rho_MFM>rho_MFM_0) = ...
%         rho_corr_nlin([rho_MFM_0 - auxnLinFit_HD.m*rho_ref_0,auxnLinFit_HD.m], ...
%         rho_MFM(rho_MFM>rho_MFM_0)-auxnLinFit_HD.RMSE);
%     expProcData.(filedataExp.Key(i)).BT.rho_corrMax(rho_MFM>rho_MFM_0) = ...
%         rho_corr_nlin([rho_MFM_0 - auxnLinFit_HD.m*rho_ref_0,auxnLinFit_HD.m], ...
%         rho_MFM(rho_MFM>rho_MFM_0)+auxnLinFit_HD.RMSE);
% end
% 

%% Add molar concentration to breakthrough data and error

x1 = 0:0.01:1; % array for binary mixture
for i = 1:length(filedataExp.Key)
    fluidPair = [filedataExp.Fluid1(i),filedataExp.Fluid2(i)];
    Tmin = floor(min(expProcData.(filedataExp.Key(i)).BT.T_MFM)*10)/10;
    Tmax = ceil(max(expProcData.(filedataExp.Key(i)).BT.T_MFM)*10)/10;
    T_PR_aux = Tmin:0.1:Tmax;
    if ismissing(trans_data_name) == 0
        Pmin = floor(min(expProcData.(filedataExp.Key(i)).BT.PT2)*10)/10;
        Pmax = ceil(max(expProcData.(filedataExp.Key(i)).BT.PT2)*10)/10;
        dPtotal = Pmax - Pmin;
        if dPtotal < 20
            P_psig = Pmin:1:Pmax;
        else
            P_psig = linspace(Pmin, Pmax, 20);
        end
        P_MPa = (P_psig + 14.7)*0.00689476;
    else
        P_psig = filedataExp.P(i);
        P_MPa = (P_psig + 14.7)*0.00689476;
    end
    PTXrho_PR_ref = table();
    for m = 1:length(T_PR_aux)
        for n = 1:length(P_MPa)
            [PR_input_T_PR_aux,PR_results_T_PR_aux] = densZ_PR(fluidPair,x1,P_MPa(n),T_PR_aux(m),filedataPure,filedataBIP);
            % Compressibility factor from Peng Robinson at T_MFM and T_mean
            Z_PR_T_PR_aux = PR_results_T_PR_aux.Z;
            % density from Peng Robinson at T_MFM and T_mean
            dens_PR_T_PR_aux = PR_results_T_PR_aux.rho;        
            % PTXrho_PR_ref table aux
            PTXrho_PR_ref_aux = table(repmat(join(fluidPair),length(x1),1), ...
                repmat(P_psig(n),length(x1),1), repmat(T_PR_aux(m),length(x1),1), x1', ...
                Z_PR_T_PR_aux, dens_PR_T_PR_aux, 'VariableNames',{'fluidPair', ...
                'P_cal_psig','T_PR', 'x_PR','Z_PR_T_PR', 'rho_PR_T_PR'});
            PTXrho_PR_ref = [PTXrho_PR_ref;PTXrho_PR_ref_aux];
        end
    end   
    % x1 interpolation function based on T and rho_corr
    scatInterp = scatteredInterpolant(PTXrho_PR_ref.T_PR, PTXrho_PR_ref.P_cal_psig, ...
        PTXrho_PR_ref.rho_PR_T_PR, PTXrho_PR_ref.x_PR, 'linear', 'linear');
    % Z interpolation function based on T and rho_corr
    scatInterpZ = scatteredInterpolant(PTXrho_PR_ref.T_PR, PTXrho_PR_ref.P_cal_psig, ...
        PTXrho_PR_ref.rho_PR_T_PR, PTXrho_PR_ref.Z_PR_T_PR, 'linear', 'linear');
    % at rho corr value
    expProcData.(filedataExp.Key(i)).BT.Ci = ...
        100*scatInterp(expProcData.(filedataExp.Key(i)).BT.T_MFM, ...
        expProcData.(filedataExp.Key(i)).BT.PT2, ...
        expProcData.(filedataExp.Key(i)).BT.rho_corr);
    % at rho min value
    expProcData.(filedataExp.Key(i)).BT.CiMax = ...
        100*scatInterp(expProcData.(filedataExp.Key(i)).BT.T_MFM, ...
        expProcData.(filedataExp.Key(i)).BT.PT2, ...
        expProcData.(filedataExp.Key(i)).BT.rho_corrMin);
    % at rho max value
    expProcData.(filedataExp.Key(i)).BT.CiMin = ...
        100*scatInterp(expProcData.(filedataExp.Key(i)).BT.T_MFM, ...
        expProcData.(filedataExp.Key(i)).BT.PT2, ...
        expProcData.(filedataExp.Key(i)).BT.rho_corrMax);
    % absolute error % 
    expProcData.(filedataExp.Key(i)).BT.dC = ...
        (abs(expProcData.(filedataExp.Key(i)).BT.CiMax ...
        -expProcData.(filedataExp.Key(i)).BT.Ci)+ ...
        abs(expProcData.(filedataExp.Key(i)).BT.CiMin ...
        -expProcData.(filedataExp.Key(i)).BT.Ci))/2;

    % at rho corr value
    expProcData.(filedataExp.Key(i)).BT.Z = ...
        scatInterpZ(expProcData.(filedataExp.Key(i)).BT.T_MFM, ...
        expProcData.(filedataExp.Key(i)).BT.PT2, ...
        expProcData.(filedataExp.Key(i)).BT.rho_corr);
    % at rho min value
    expProcData.(filedataExp.Key(i)).BT.ZMax = ...
        scatInterpZ(expProcData.(filedataExp.Key(i)).BT.T_MFM, ...
        expProcData.(filedataExp.Key(i)).BT.PT2, ...
        expProcData.(filedataExp.Key(i)).BT.rho_corrMin);
    % at rho max value
    expProcData.(filedataExp.Key(i)).BT.ZMin = ...
        scatInterpZ(expProcData.(filedataExp.Key(i)).BT.T_MFM, ...
        expProcData.(filedataExp.Key(i)).BT.PT2, ...
        expProcData.(filedataExp.Key(i)).BT.rho_corrMax);
    % absolute error 
    expProcData.(filedataExp.Key(i)).BT.dZ = ...
        abs(expProcData.(filedataExp.Key(i)).BT.ZMax ...
        -expProcData.(filedataExp.Key(i)).BT.ZMin)/2;

    % dimensionless values 
    % td = Q t / V
    expProcData.(filedataExp.Key(i)).BT.tD = ... % in respect to Vcore
        expProcData.(filedataExp.Key(i)).BT.SecondsElapsed*filedataExp.Q(i)/...
        (60*filedataExp.Vcore(i));

    expProcData.(filedataExp.Key(i)).BT.tDtotal = ... % in respect to Vtotal
        expProcData.(filedataExp.Key(i)).BT.SecondsElapsed*filedataExp.Q(i)/...
        (60*filedataExp.Vtotal(i));

    T_K_real = expProcData.(filedataExp.Key(i)).BT.T_MFM + 275.15;
    T_K_base = 25 + 275.15;
    P_MPa_base = (0 + 14.7)*0.00689476;

    % expProcData.(filedataExp.Key(i)).BT.tDZ = ... % in respect to Vcore
    %     expProcData.(filedataExp.Key(i)).BT.SecondsElapsed*filedataExp.Q(i)./...
    %     (60*(expProcData.(filedataExp.Key(i)).BT.Z.*(T_K_real/T_K_base)*(P_MPa_base/P_MPa)*filedataExp.Vcore(i)));
    % 
    % expProcData.(filedataExp.Key(i)).BT.tDZtotal = ... % in respect to Vcore
    %     expProcData.(filedataExp.Key(i)).BT.SecondsElapsed*filedataExp.Q(i)./...
    %     (60*(expProcData.(filedataExp.Key(i)).BT.Z).*(T_K_real/T_K_base)*(P_MPa_base/P_MPa)*filedataExp.Vtotal(i));
    
    % Cd = (C - Ciinit) / (Cj - Cinit)
    expProcData.(filedataExp.Key(i)).BT.CDi = ...
        (expProcData.(filedataExp.Key(i)).BT.Ci - filedataExp.C1init(i))/(filedataExp.C1j(i)-filedataExp.C1init(i));

    expProcData.(filedataExp.Key(i)).BT.CDiMax = ...
        (expProcData.(filedataExp.Key(i)).BT.CiMax - filedataExp.C1init(i))/(filedataExp.C1j(i)-filedataExp.C1init(i));

    expProcData.(filedataExp.Key(i)).BT.CDiMin = ...
        (expProcData.(filedataExp.Key(i)).BT.CiMin - filedataExp.C1init(i))/(filedataExp.C1j(i)-filedataExp.C1init(i));

end

save(pathExportAll + "expProcData.mat",'expProcData')

%% Save data

for i = 1:length(filedataExp.Key)
    delete(pathExportAll + filedataExp.Key(i) + '.xlsx')

    writetable(expProcData.(filedataExp.Key(i)).pumpsData,pathExportAll + filedataExp.Key(i) + '.xlsx', 'Sheet', 'pumps_data');
    writetable(expProcData.(filedataExp.Key(i)).transData,pathExportAll + filedataExp.Key(i) + '.xlsx', 'Sheet', 'trans_data');
    writetable(expProcData.(filedataExp.Key(i)).MFMData,pathExportAll + filedataExp.Key(i) + '.xlsx', 'Sheet', 'MFM_data');
    if ismissing(PGD1_data_name) == 0
        writetable(expProcData.(filedataExp.Key(i)).PGD1Data,pathExportAll + filedataExp.Key(i) + '.xlsx', 'Sheet', 'PGD1_data');
    end
    if ismissing(PGD2_data_name) == 0
        writetable(expProcData.(filedataExp.Key(i)).PGD2Data,pathExportAll + filedataExp.Key(i) + '.xlsx', 'Sheet', 'PGD2_data');
    end
    writetable(expProcData.(filedataExp.Key(i)).exp_params,pathExportAll + filedataExp.Key(i) + '.xlsx', 'Sheet', 'exp_params');
    writetable(expProcData.(filedataExp.Key(i)).BT,pathExportAll + filedataExp.Key(i) + '.xlsx', 'Sheet', 'BT_curve');
end

%% Plots for analysis

% Subplot all in 5 panels
for i = 1:length(filedataExp.Key)
    
    pumps_data_name = filedataExp.path(i) + filedataExp.pumps_data_name(i);
    trans_data_name = filedataExp.path(i) + filedataExp.trans_data_name(i);
    MFM_data_name = filedataExp.path(i) + filedataExp.MFM_data_name(i);
    PGD1_data_name = filedataExp.path(i) + filedataExp.PGD1_data_name(i);
    PGD2_data_name = filedataExp.path(i) + filedataExp.PGD2_data_name(i);

    figure('Position', [100, 100, 600, 900]); % [left, bottom, width, height];
    subplot(5,1,1);
    if isempty(expProcData.(filedataExp.Key(i)).transData) == 0 && ismissing(trans_data_name) == 0
        scatter(expProcData.(filedataExp.Key(i)).transData.TimeElapsed,expProcData.(filedataExp.Key(i)).transData.PT1,10,'filled','DisplayName','PT1')
        hold on
        scatter(expProcData.(filedataExp.Key(i)).transData.TimeElapsed,expProcData.(filedataExp.Key(i)).transData.PT2,10,'filled','DisplayName','PT2')
    end
    % xlabel('Time elapsed [hh:mm:ss]')
    ylabel('Pressure [psig]')
    xtickformat('hh:mm:ss')
    Pavelim = mean((expProcData.(filedataExp.Key(i)).transData.PT1 + expProcData.(filedataExp.Key(i)).transData.PT2)/2);
    ylim([Pavelim - 100,Pavelim + 100])
    grid("on")
    title(filedataExp.Key(i) + " pore pressure", 'Interpreter', 'none')
    legend('Location','southeast');

    subplot(5,1,2);
    if isempty(expProcData.(filedataExp.Key(i)).pumpsData) == 0 && ismissing(pumps_data_name) == 0
        scatter(expProcData.(filedataExp.Key(i)).pumpsData.TimeElapsed,expProcData.(filedataExp.Key(i)).pumpsData.P_Pconf,10,'filled','DisplayName','Pconf')
    end
    % xlabel('Time elapsed [hh:mm:ss]')
    ylabel('Pressure [psig]')
    xtickformat('hh:mm:ss')
    Pconfavg = mean(expProcData.(filedataExp.Key(i)).pumpsData.P_Pconf);
    ylim([Pconfavg-300,Pconfavg+300])
    grid("on")
    title(filedataExp.Key(i) + " confining pressure", 'Interpreter', 'none')
    legend('Location','southeast');

    subplot(5,1,3);
    if isempty(expProcData.(filedataExp.Key(i)).pumpsData) == 0 && ismissing(pumps_data_name) == 0
        scatter(expProcData.(filedataExp.Key(i)).pumpsData.TimeElapsed,expProcData.(filedataExp.Key(i)).pumpsData.Q_Pworking,10,'filled','DisplayName','q_{pump}')
        hold on
    end
    if isempty(expProcData.(filedataExp.Key(i)).MFMData) == 0
        scatter(expProcData.(filedataExp.Key(i)).MFMData.TimeElapsed,expProcData.(filedataExp.Key(i)).MFMData.q_MFM2,10,'filled','DisplayName','q_{MFM}')
    end
    xlabel('Time elapsed [hh:mm:ss]')
    xtickformat('hh:mm:ss')
    ylim([-1,15])
    ylabel('Flow rate [ml/min]')
    grid on;
    title(filedataExp.Key(i) + " flow rates", 'Interpreter', 'none')
    legend('Location','southeast');

    subplot(5,1,4);
    yyaxis left
    ax = gca;
    ax.YColor = [0 0 0];
    scatter(expProcData.(filedataExp.Key(i)).BT.TimeElapsed,expProcData.(filedataExp.Key(i)).BT.rho_corr,10,'filled','MarkerFaceColor','r')
    hold on
    xlabel('Time elapsed [hh:mm:ss]')
    xtickformat('hh:mm:ss')
    ylabel('\rho_{corr} [kg/m^{3}]');
    yyaxis right
    ax = gca;
    ax.YColor = [0 0 0];
    ylabel('Temperature [°C]');
    scatter(expProcData.(filedataExp.Key(i)).BT.TimeElapsed,expProcData.(filedataExp.Key(i)).BT.T_MFM,10,'filled', 'MarkerFaceColor',[0.9290, 0.6940, 0.1250])
    legend('\rho_{corr}','T_{MFM}', 'Location','southeast');
    title(filedataExp.Key(i) + " density and temperature", 'Interpreter', 'none')
    grid on;

    subplot(5,1,5);
    yyaxis left
    ax = gca;
    ax.YColor = [0 0 0];
    ylabel('C1_{PGDs} [mol %]');
    ylim([0,100])
    hold on
    if ismissing(PGD2_data_name) == 0
        scatter(expProcData.(filedataExp.Key(i)).PGD2Data.TimeElapsed,expProcData.(filedataExp.Key(i)).PGD2Data.C1,10,'filled', 'MarkerFaceColor',[0.0000 0.4470 0.7410], 'DisplayName','C1_{PGD2}')
        hold on
    end
    if ismissing(PGD1_data_name) == 0
        scatter(expProcData.(filedataExp.Key(i)).PGD1Data.TimeElapsed,expProcData.(filedataExp.Key(i)).PGD1Data.C1,10,'filled','MarkerFaceColor', [0.9290 0.6940 0.1250], 'DisplayName','C1_{PGD1}')
        hold on
    end
    yyaxis right
    ax = gca;
    ax.YColor = [0 0 0];
    scatter(expProcData.(filedataExp.Key(i)).BT.TimeElapsed,expProcData.(filedataExp.Key(i)).BT.Ci,10,'filled','MarkerFaceColor','r','DisplayName','C1_{MFM}')
    hold on
    xlabel('Time elapsed [hh:mm:ss]')
    xtickformat('hh:mm:ss')
    ylabel('C1_{MFM} [mol %]');
    ylim([0,100])
    legend('Location','southeast');
    title(filedataExp.Key(i) + " molar concentrations", 'Interpreter', 'none')
    grid on;

    saveas(gcf,pathExportAll + filedataExp.Key(i) + "_BT_All_Vars",'png')
end

%% Plot concentration molar all together
for i = 1:length(filedataExp.Key)
    pumps_data_name = filedataExp.path(i) + filedataExp.pumps_data_name(i);
    trans_data_name = filedataExp.path(i) + filedataExp.trans_data_name(i);
    MFM_data_name = filedataExp.path(i) + filedataExp.MFM_data_name(i);
    PGD1_data_name = filedataExp.path(i) + filedataExp.PGD1_data_name(i);
    PGD2_data_name = filedataExp.path(i) + filedataExp.PGD1_data_name(i);
    % Densities and concentrations PGD
    figure('Position', [100, 100, 700, 550]);
    tiledlayout(2,2, 'TileSpacing', 'tight', 'Padding','tight');
    if ismissing(MFM_data_name) == 0
        t = expProcData.(filedataExp.Key(i)).BT.TimeElapsed;
        C1 = expProcData.(filedataExp.Key(i)).BT.Ci;
        C1min = expProcData.(filedataExp.Key(i)).BT.CiMin;
        C1max = expProcData.(filedataExp.Key(i)).BT.CiMax;
        errorbar(t, C1, C1-C1min, C1max - C1, 'LineStyle', 'none', 'Color', [255 193 183]/255,'HandleVisibility','off')
        hold on 
        h3 = scatter(t,C1,5,'filled','MarkerFaceColor','r','DisplayName','C_{MFM} \pm \DeltaC_{MFM}');
    end
    if ismissing(PGD2_data_name) == 0
        h1 = scatter(expProcData.(filedataExp.Key(i)).PGD2Data.TimeElapsed,expProcData.(filedataExp.Key(i)).PGD2Data.C1,7,'filled','MarkerFaceColor',[0.9290 0.6940 0.1250],'DisplayName','C_{PGD2}');
        hold on 
    end
    if ismissing(PGD1_data_name) == 0
        h2 = scatter(expProcData.(filedataExp.Key(i)).PGD1Data.TimeElapsed,expProcData.(filedataExp.Key(i)).PGD1Data.C1,7,'filled','MarkerFaceColor',[0.4660    0.6740    0.1880],'DisplayName','C_{PGD1}');
        hold on 
    end
    xlabel('Time elapsed [hh:mm:ss]','FontSize', 14);
    xtickformat('hh:mm:ss')
    ylabel('C_{H_2} [mol %]','FontSize', 14);
    ylim([0,100]);
    lgd = legend('Location','southeast','FontSize',14);
    title (lgd, "Q = " + filedataExp.Q(i) + " ml/min",'FontSize',14)
    grid on;
    ax = gca; % Get current axes
    ax.FontSize = 14;
    saveas(gcf,pathExportAll + filedataExp.Key(i) + "_dens_conc",'png')
end
